export const FETCH_APPLICATION_DATA = "FETCH_APPLICATION_DATA";
export const UPDATE_APPLICATION_DATA = "UPDATE_APPLICATION_DATA";
export const FAILURE_RECEIVE_APPLICATION_DATA =
  "FAILURE_RECEIVE_APPLICATION_DATA";
