export const FETCH_SLIDER_DATA = "FETCH_SLIDER_DATA";
export const SET_SLIDER_DATA = "SET_SLIDER_DATA";
export const SET_SLIDER_LINK = "SET_SLIDER_LINK";
export const FAILURE_RECEIVE_SLIDER_DATA = "FAILURE_RECEIVE_SLIDER_DATA";
